### ISSUE TITLE
Not able to view data retrived from database in IST timezone.

### ISSUE THREAD

**Issue by yashmane** [8gears/plausible-analytics-helm-chart#9]
Graph mapping is not according to the timezone which is selected in graph's setting >> Timezone.
Selecting timezone (GMT +5:30) Chennai, Kolkata, Mumbai, Delhi.
Resulting behavior:
The graph plotted at IST -5:30
Expected behavior:
The graph should be plotted at the above selected timezone.

Could someone help me understand why is this happening and also what is the exact flow/calls made in plausible. How plausible communicates with postgres and clickhouse databases.

For now we have made changes in clickhouse database to store data in 00:00 GMT and in plausible selected +5:30 GMT Now it shows correct plotting.

**Comment by Vad1mo** [comment]
you can set the time zones individually on clickhouse and postgres

see this example how we set the time zone for clickhouse.
https://github.com/8gears/plausible-analytics-helm-chart/blob/main/helmfile.yaml#L63

Also the timezone can be set on the plausible website: https://plausible.io/docs/general

**Comment by yashmane** [comment]
Hi @Vad1mo 
We are not using helmfile.
We are deploying using helm chart and have changed timezone in plausible website.
Also have made changes in clickhouse database but still cannot see correct plotting.

Do you have any other suggestions?

**Comment by Vad1mo** [comment]
the clickhouse configuration doesn't have any relation to the helmfile. 

You need to changes the tim zone in the config of the clickhouse. I don't know how you are deploying clickhouse or with what chart. The deployment config of your clickhouse should have an entry regarding the time zone.

**Comment by yashmane** [comment]
Yes have made changes related to timezone in clickhouse's config
## Timezone
#timezone: "Asia/Shanghai"
timezone: "Asia/Kolkata"
Above snippet from clickhouse config file

Below is screenshot of selected timezone
![Screenshot from 2021-05-12 18-45-11](https://user-images.githubusercontent.com/25627564/117981319-82517a00-b352-11eb-8cbb-22950e970dcb.png)

we visited our website on around 5pm and the graph which is plotted is at 12PM
Below if the screenshot for the same.

![Screenshot from 2021-05-12 18-48-52](https://user-images.githubusercontent.com/25627564/117981871-13c0ec00-b353-11eb-845b-776415559a88.png)


Do let me know if you require any input from my end.

**Comment by Vad1mo** [comment]
I don't know. This is just a guess, maybe it is set only once and later changes are ignored. I don't know the reason or what is the exact problem, but it's not related to the Helm chart here as settings are forwareded 1:1!

**Comment by yashmane** [comment]
Okay,
Thanks for help.
